name: wifi_controller_plugin
description: Flutter plugin that allows control some wifi related actions
version: 0.2.0

environment:
  sdk: ">=2.10.2 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.justd.wifi_controller_plugin
        pluginClass: WifiControllerPlugin
      ios:
        pluginClass: WifiControllerPlugin